repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.16 # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
    hooks:
      - id: helmlint
  - repo: https://github.com/norwoodj/helm-docs
      rev: v1.2.0
      hooks:
        - id: helm-docs
